language: python
python:
  - 2.7
  - 3.5

install:
  - pip install -r requirements.txt
  - pip install --upgrade .

script:
  - py.test tests/ -q -r fEsxXw --strict

after_success:
  - coverage combine
  - codecov

#notifications:
#  email: false

branches:
  only:
    - master
